import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { DemoBadge } from "@/components/ui/demo-badge";
import type { Finding, Report, ReportSection, Site } from "@/lib/types/domain";

export function ReportView({
  report,
  site,
  sections,
  showDemoBadge,
  printMode = false,
}: {
  report: Report;
  site: Site;
  sections: ReportSection[];
  showDemoBadge: boolean;
  printMode?: boolean;
}) {
  return (
    <article className={printMode ? "max-w-4xl mx-auto py-8 px-4 bg-white" : ""}>
      <header className="border-b border-[var(--color-line)] pb-4 mb-6">
        <div className="text-xs uppercase tracking-wider text-[var(--color-muted)] font-bold mb-2">
          Weekly Organic Growth Brief
        </div>
        <h1 className="font-serif text-3xl font-semibold text-[var(--color-ink)] leading-tight">{report.title}</h1>
        <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-[var(--color-ink-3)]">
          <span><span className="text-[var(--color-muted)]">Site:</span> {site.name} · {site.url}</span>
          <span><span className="text-[var(--color-muted)]">Period:</span> {report.period_start} → {report.period_end}</span>
          {showDemoBadge && <DemoBadge />}
        </div>
      </header>

      <section className="mb-6">
        <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-2">Executive summary</h2>
        <p className="font-serif text-base text-[var(--color-ink-2)] leading-relaxed">{report.executive_summary}</p>
      </section>

      {sections
        .filter((s) => s.section_key !== "executive_summary")
        .map((section) => {
          const items = (section.body as { items?: Finding[] }).items ?? [];
          return (
            <section key={section.id} className="mb-6 break-inside-avoid">
              <h2 className="font-serif text-lg font-semibold text-[var(--color-ink)] mb-3 border-b border-[var(--color-line-soft)] pb-1">
                {section.title}
              </h2>
              {items.length === 0 ? (
                <p className="text-sm text-[var(--color-muted)] italic">No findings in this section.</p>
              ) : (
                <div className="grid gap-3">
                  {items.map((f) => (
                    <Card key={f.id} className="break-inside-avoid">
                      <CardContent className="py-3">
                        <div className="flex items-start justify-between gap-3 mb-2 flex-wrap">
                          <h3 className="font-serif font-semibold text-[var(--color-ink)] text-base">{f.title}</h3>
                          <div className="flex flex-wrap gap-1">
                            <Badge variant={f.priority}>{f.priority.toUpperCase()}</Badge>
                            <Badge variant="neutral">Impact {f.impact_score}/5</Badge>
                            <Badge variant="neutral">Effort {f.effort_score}/5</Badge>
                            <Badge variant="neutral">{f.confidence}</Badge>
                          </div>
                        </div>
                        <dl className="text-sm text-[var(--color-ink-2)] grid sm:grid-cols-[120px_1fr] gap-y-1 gap-x-4">
                          <dt className="text-[10px] uppercase font-bold text-[var(--color-muted)] tracking-wider pt-0.5">Why it matters</dt>
                          <dd>{f.why_it_matters}</dd>
                          <dt className="text-[10px] uppercase font-bold text-[var(--color-muted)] tracking-wider pt-0.5">Recommended action</dt>
                          <dd>{f.recommended_action}</dd>
                        </dl>
                        <p className="text-xs italic text-[var(--color-muted)] mt-2">{f.score_explanation}</p>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </section>
          );
        })}

      <footer className="text-xs text-[var(--color-muted)] mt-8 pt-3 border-t border-[var(--color-line)]">
        Generated by Weekly Organic Growth Brief · Report period {report.period_start} → {report.period_end}
        {showDemoBadge && " · Brief built from demo data."}
      </footer>
    </article>
  );
}
